monitor/web/router.ex
defmodule Monitor.Router do
  use Monitor.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Monitor do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/servers/:id/active", ServerController, :active
    resources "/users", UserController
    resources "/servers", ServerController
    resources "/services", ServiceController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Monitor do
  #   pipe_through :api
  # end
end

monitor/web/views/layout_view.ex
defmodule Monitor.LayoutView do
  use Monitor.Web, :view
end

monitor/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="https://code.jquery.com/jquery-1.12.3.min.js" integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ=" crossorigin="anonymous"></script>
    <title>Hello Monitor!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <nav role="navigation">
          <ul class="nav nav-pills">
            <li><%= link "Servers", to: server_path(@conn, :index) %></li>
            <li><%= link "Services", to: service_path(@conn, :index) %></li>
            <li><%= link "Users", to: user_path(@conn, :index) %></li>
          </ul>
        </nav>
        <div class="server-alert alert alert-danger" style="display: none">
          <br>
          <strong>Oops!</strong> The Monitor Application is Down!
          <br>
          <br>
        </div>

        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>